branch-defaults:
  default:
    environment: null
    group_suffix: null
  master:
    environment: my-web-app-dev
deploy:
  artifact: target/demo-aws-0.0.1-SNAPSHOT.jar
global:
  application_name: my-web-app
  branch: null
  default_ec2_keyname: key
  default_platform: Corretto 11 running on 64bit Amazon Linux 2
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
